[envs.test]
python = "3.12"
detached = true
dependencies = [
  "ansible==10.4.0",
  "molecule==24.9.0",
  "molecule-plugins[podman]==23.5.3",
  ]

[envs.test.scripts]
test = "molecule test {args}"
create = "molecule create {args}"
converge = "molecule converge {args}"
verify = "molecule verify {args}"
destroy = "molecule destroy {args}"

[envs.lint]
detached = true
dependencies = [
  "ansible-lint==24.9.2",
  "yamllint==1.34.0"
  ]

[envs.lint.scripts]
yaml = "yamllint -s tasks/ molecule/ meta/"
ansible = "ansible-lint --exclude molecule/ --exclude meta"
all = ["yaml", "ansible"]

[envs.docs]
detached = true
dependencies = ["aar-doc==2.0.0"]

[envs.docs.scripts]
generate = "aar-doc . markdown"
