FROM quay.io/podman/stable:v5.2

RUN dnf install -y systemd python3 python3-pip && dnf clean all

RUN mkdir -p /home/podman/.config/systemd/user /home/podman/.config/containers/systemd

RUN mkdir -p /var/lib/systemd/linger && \
    touch /var/lib/systemd/linger/podman && \
    chown -R 1000:1000 /home/podman

ENTRYPOINT /sbin/init

