---
role_name_check: 1
driver:
  name: podman
platforms:
  - name: instance
    image: selfhosted-pinp-container:latest
    privileged: true
    pre_build_image: false
    dockerfile: CONTAINERFILE
    systemd: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_user: podman
verifier:
  name: ansible
