---
role_name_check: 1
driver:
  name: podman
platforms:
  - name: instance
    image: registry.access.redhat.com/ubi9/ubi-init:latest
    command: ""
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
