---
name: Test Template

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: test-template-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  Template-test:
    name: Template testing
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'    
      - name: Install dependencies
        run: |
          apt install -y git
          pip install -U pip
          pip install --upgrade copier==9.3.1 hatch==1.13.0
      - name: Copy template
        run: >
          copier copy -f --trust -r HEAD . ../new_template \
            -d namespace_name="namespace" \
            -d author_name="authorname" \
            -d author_email="email@example.com" \
            -d author_company="" \
            -d role_name="rolename" \
            -d collection_name="collectionname" \
            -d license="MIT" \
            -d copyright_holder="authorname" \
            -d short_description="Short description" \
            -d repository_host="codeberg.org" \
            -d repository_url="https://www.github.com/company/repository"
      - name: Run tests
        working-directory: ../new_template
        run: hatch run test:action

  Template-lint:
    name: Template linting
    runs-on: ubuntu-latest
    container:
      image: "quay.io/speakintelnet/pinp-molecule"
      options: "
        --security-opt label=disabled
        --security-opt seccomp=unconfined
        --privileged
        "
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo dnf install -y git
          pip3 install --upgrade copier==9.3.1 hatch==1.13.0
      - name: Copy template
        run: >
          copier copy -f --trust -r HEAD . ../new_template \
            -d namespace_name="namespace" \
            -d author_name="authorname" \
            -d author_email="email@example.com" \
            -d author_company="" \
            -d role_name="rolename" \
            -d collection_name="collectionname" \
            -d license="MIT" \
            -d copyright_holder="authorname" \
            -d short_description="Short description" \
            -d repository_host="codeberg.org" \
            -d repository_url="https://www.github.com/company/repository"
      - name: run lints
        working-directory: ../new_template
        run: hatch run lint:all

  Template-readme:
    name: Generate readme file
    runs-on: ubuntu-latest
    container:
      image: "quay.io/speakintelnet/pinp-molecule"
      options: "
        --security-opt label=disabled
        --security-opt seccomp=unconfined
        --privileged
        "
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo dnf install -y git
          pip3 install --upgrade copier==9.3.1 hatch==1.13.0
      - name: Copy template
        run: >
          copier copy -f --trust -r HEAD . ../new_template \
            -d namespace_name="namespace" \
            -d author_name="authorname" \
            -d author_email="email@example.com" \
            -d author_company="" \
            -d role_name="rolename" \
            -d collection_name="collectionname" \
            -d license="MIT" \
            -d copyright_holder="authorname" \
            -d short_description="Short description" \
            -d repository_host="codeberg.org" \
            -d repository_url="https://www.github.com/company/repository"
      - name: run lints
        working-directory: ../new_template
        run: hatch run docs:generate
      - id: set_content
        name: read content of readme file
        working-directory: ../new_template
        run: |
          content=`cat README.md`
          echo readme_content=$content >> $GITHUB_ENV
      - name: check content of readme file
        if: contains(env.readme_content, 'Main entry point for the rolename role') != true
        run: |
          exit 1
      - name: print message if readme file is correct
        run: |
          echo "README.md was generated properly"
