---
name: Test Template

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: test-template-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  Template-test:
    name: Template testing
    runs-on: ubuntu-22.04
    container:
      image: catthehacker/ubuntu:act-22.04@sha256:89367f3c5437699c6b43fa941041725bcc77682a46f2bbe6557541e384d9cedb
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"
      - name: Install dependencies
        run: |
          apt install -y git
          pip install -U pip
          pip install --upgrade copier==9.3.1 hatch==1.13.0
      - name: Copy template
        run: >
          copier copy -f --trust -r HEAD . ../new_template \
            -d author_name="authorname" \
            -d author_email="email@example.com" \
            -d author_company="" \
            -d role_name="rolename" \
            -d related_url="example.com" \
            -d collection_name="services" \
            -d license="MIT" \
            -d copyright_holder="authorname" \
            -d short_description="Short description" \
            -d repository_host="codeberg.org" \
            -d repository_url="https://www.github.com/company/repository"
      - name: Run tests
        working-directory: ../new_template
        run: hatch run test:action

  Template-lint:
    name: Template linting
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-22.04@sha256:89367f3c5437699c6b43fa941041725bcc77682a46f2bbe6557541e384d9cedb
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"
      - name: Install dependencies
        run: |
          apt install -y git
          pip install -U pip
          pip install --upgrade copier==9.3.1 hatch==1.13.0
      - name: Copy template
        run: >
          copier copy -f --trust -r HEAD . ../new_template \
            -d author_name="authorname" \
            -d author_email="email@example.com" \
            -d author_company="" \
            -d role_name="rolename" \
            -d related_url="example.com" \
            -d collection_name="services" \
            -d license="MIT" \
            -d copyright_holder="authorname" \
            -d short_description="Short description" \
            -d repository_host="codeberg.org" \
            -d repository_url="https://www.github.com/company/repository"
      - name: run lints
        working-directory: ../new_template
        run: hatch run lint:lint

  Template-readme:
    name: Generate readme file
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-22.04@sha256:89367f3c5437699c6b43fa941041725bcc77682a46f2bbe6557541e384d9cedb
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"
      - name: Install dependencies
        run: |
          apt install -y git
          pip install -U pip
          pip install --upgrade copier==9.3.1 hatch==1.13.0
      - name: Copy template
        run: >
          copier copy -f --trust -r HEAD . ../new_template \
            -d author_name="authorname" \
            -d author_email="email@example.com" \
            -d author_company="" \
            -d role_name="rolename" \
            -d related_url="example.com" \
            -d collection_name="services" \
            -d license="MIT" \
            -d copyright_holder="authorname" \
            -d short_description="Short description" \
            -d repository_host="codeberg.org" \
            -d repository_url="https://www.github.com/company/repository"
      - name: generate readme
        working-directory: ../new_template
        run: hatch run docs:readme
      - id: set_content
        name: read content of readme file
        working-directory: ../new_template
        run: |
          content=`cat README.md`
          echo readme_content=$content >> $GITHUB_ENV
      - name: check content of readme file for description
        if: contains(env.readme_content, 'Short description') != true
        run: |
          exit 1
      - name: check content of readme file for role name
        if: contains(env.readme_content, 'rolename') != true
        run: |
          exit 1
      - name: print message if readme file is correct
        run: |
          echo "README.md was generated properly"
