---

name: CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: install yamllint
        run: pip install yamllint

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: "--exclude molecule/ --exclude meta/"       

      - name: Run yamllint
        run: yamllint -s .

  build:
    name: Molecule Tests
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Test with molecule
        run: |
          molecule test
